version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
  web:
    build:
      context: .
      dockerfile: infra/Dockerfile.web
    depends_on:
      - api
    ports:
      - "3000:80"
volumes:
  db-data:
