FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json pnpm-workspace.yaml ./
COPY packages packages
COPY apps/api apps/api
RUN corepack enable && pnpm install --filter ./apps/api --prod && pnpm --filter ./apps/api build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/apps/api/package.json ./package.json
RUN corepack enable && pnpm install --prod
CMD ["node", "dist/index.js"]
